# -*- coding: utf-8 -*-
"""Orbital Modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZcmpaAbdeYN4EzFzLB6vcj7VW300nRP

TODO:
*   Keep lowering loss

Long Term (keep list for thesis)

* Train on data in relative coordinates maybe with a target radius value
*   Obvious easy change: cap binary search with LSTM bad guess
*   No time dependance
"""
#imports
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import norm
import os

from scipy.signal import cont2discrete
from scipy.linalg import solve_discrete_are
from globals import mu, indexInterp, ECI2RIC, ECIprop, rainbow_plot
from globals import gravity_gradient 

a_target = 7000 #km
n=np.sqrt(mu/a_target**3)
T_target = 2*np.pi*np.sqrt(a_target**3/mu)
step = 1 #seconds
kx = 10 #From paper, required for K calc
kv = 1
ku = 1
Q = np.block([[kx*np.eye(3), np.zeros((3,3))],[np.zeros((3,3)), kv*np.eye(3)]])
R = ku*np.eye(3)
conehalfangle = 20*np.pi/180 #half angle in radians the chaser must stay within.
g1=5 #km when constraint kicks in
g2=20 #Paper says rad/sec, I think its (km/s)/km
g3=0.001 #km/sec speed limit at dist 0.
totalsimorbits = 0

tx0 = np.array([a_target,0,0])
tv0 = np.array([0,np.sqrt(mu/norm(tx0)),0])

tx=tx0.copy()
tv=tv0.copy()
#Compute n orbits of gains and target states
n=3

stepsPerOrbit = int(T_target//step)


if os.path.exists("localsaves/precompute.npz"):
    with open("localsaves/precompute.npz","rb") as f:
        zvars = np.load(f)
        if zvars["a_target"] != a_target or zvars["step"] != step:
            raise ValueError('step size and a_target must match current script. a_target:'+
                             f' {a_target} != {zvars["a_target"]} or step: {step} != {zvars["step"]}')
        K = zvars["K"]
        t_hist = zvars["t_hist"]
        print("Loaded t_hist and K from file localsaves/precompute.npz")
else: 
    t_hist = np.zeros((n*stepsPerOrbit,2,3))
    K = np.zeros((n*stepsPerOrbit,3,6))
    B_cont = np.block([[np.zeros((3,3))],[np.eye((3))]])
    print("Calculating precomputed t_hist and K values...")
    print("-"*int(2+np.floor((n*stepsPerOrbit)/1000)))
    for i in range(n*stepsPerOrbit):
        if i%1000 == 0:
          print("-", end="")
        t_hist[i,0,:] = tx
        t_hist[i,1,:] = tv
        g = gravity_gradient(tx)
        A_cont = np.block([[np.zeros((3,3)), np.eye(3)],[g, np.zeros((3,3))]])
        discreteTuple = cont2discrete((A_cont, B_cont, np.eye(6), np.zeros((6,3))), step)
        A_disc = discreteTuple[0]
        B_disc = discreteTuple[1]
        St=solve_discrete_are(A_disc, B_disc, Q, R)
        Kt=np.linalg.inv(B_disc.T @ St @ B_disc) @ B_disc.T @ St @ A_disc
        K[i,:] = Kt
        tx,tv = ECIprop(tx, tv, step)
    print("-", end="")
    if "thesis" in os.getcwd() or "Thesis" in os.getcwd():
        print("Saved into localsaves/precompute.npz")
        np.savez("localsaves/precompute.npz", K=K, t_hist=t_hist, a_target=a_target, step=step)

initAngle = .2 #neg in track
amultchaser = 1.005 #SMA ratio chaser/target
zoffset = 0
orbits = .02

cx0 = np.array([amultchaser*a_target*np.cos(-initAngle),amultchaser*a_target*np.sin(-initAngle),zoffset])
cv0mag = np.sqrt(mu/norm(cx0))
cv0 = np.array([-cv0mag*np.sin(-initAngle),cv0mag*np.cos(-initAngle),0])
unext = np.zeros((3,1)) #First Timestep, just use zero accel

initdists = norm(t_hist[0:stepsPerOrbit,0,:]-cx0,axis=1)
tback0 = stepsPerOrbit - np.argmin(initdists) + 1

#Initialize states for this run
tx=t_hist[stepsPerOrbit,0,:]
tv=t_hist[stepsPerOrbit,1,:]
cx=cx0.copy()
cv=cv0.copy()
tback=tback0

steps = int(orbits*T_target)//step
#At time 0, tx is at t_hist[stepsperorbit]
if np.size(t_hist,axis=0) < (2*stepsPerOrbit)+steps:
    raise ValueError("Need longer precompute")

def OneOrbitNoLog(i0, cx0, cv0, testTback):
    global totalsimorbits
    totalsimorbits += 1
    cxsim = cx0.copy()
    cvsim = cv0.copy()
    txsim = t_hist[stepsPerOrbit+i0,0,:]
    tvsim = t_hist[stepsPerOrbit+i0,1,:]
    success = True
    for j in range(i0,i0+stepsPerOrbit):
        speedconst = norm(cvsim-tvsim) - (g2*norm(cxsim-txsim)) - g3 if norm(cxsim-txsim) <= g1  and norm(cxsim-txsim)>1e-3 else 0
        normedpos = (cxsim-txsim)/norm(cxsim-txsim)
        coneconst = -1*(( -tvsim.T @ normedpos) / (norm(tvsim))) + np.cos(conehalfangle) if norm(cxsim-txsim)>1e-3 else 0
        if speedconst > 0 or coneconst > 0:
            if j==i:
                raise ValueError("Error, const already broken shouldnt be possible")
            success = False
            break
        tsgIndex = stepsPerOrbit + j - testTback
        Kt = indexInterp(K, tsgIndex, 0)
        tstate = indexInterp(t_hist, tsgIndex, 0);
        unext = -Kt@np.hstack([cxsim-tstate[0,:], cvsim-tstate[1,:]])
        if norm(unext)>.5:
            unext = unext * (.5/norm(unext))
        txsim = t_hist[stepsPerOrbit+j+1,0,:]
        tvsim = t_hist[stepsPerOrbit+j+1,1,:]
        cxsim,cvsim = ECIprop(cxsim, cvsim, step, accel=unext)
    return success

#Initialize lists for plotting
c_hist = np.zeros((steps,2,3)) # Shape (n, 2, 3)
c_hist_ric = np.zeros((steps,2,3))
tenergyhist = np.zeros((steps,1)) # Shape (n,)
umaghist = np.zeros((steps,1)) # Shape (n,)
coneconsthist = np.zeros((steps,1)) # Shape (n,)
speedconsthist = np.zeros((steps,1)) # Shape (n,)
tbackhist = np.zeros((steps,1)) # Shape (n,)
print("Running Simulation...")
print("-"*(2+(steps//10)))
for i in range(steps):
    if i%10==0 or i==steps-1:
        print("-",end="")
  ######### Logging ###########
    c_hist[i,0,:] = cx
    #c_hist[i,1,:] = cv
    Tmat = ECI2RIC(tx, tv)
    c_hist_ric[i,0,:] = Tmat @ (cx-tx)
    c_hist_ric[i,1,:] = Tmat @ (cv-tv)
    #tenergyhist[i] = 0.5*norm(tv)**2 - (mu/norm(tx))
    umaghist[i] = norm(unext)
    coneconsthist[i] = -1*(( -tv.T @ (cx-tx)/norm(cx-tx)) / (norm(tv))) + np.cos(conehalfangle) if norm(cx-tx)>1e-3 else 0
    speedconsthist[i] = norm(cv-tv) - (g2*norm(cx-tx)) - g3 if norm(cx-tx) <= g1 and norm(cx-tx)>1e-3 else 0
    tbackhist[i] = tback
  ######### Control Calc ###########
    mint = 0.0001 #s
    maxt = tback #from last propagation
    if tback > 2:
        thresh = .5
    elif tback < 2:
        thresh = .01
    elif tback < .5:
        thresh = 0
        maxt = 0
    while maxt - mint > thresh:
        testTback = (maxt+mint)/2
        txsim = tx.copy()
        tvsim = tv.copy()
        success = OneOrbitNoLog(i, cx, cv, testTback)
        if success:
            maxt = testTback #consts met
        else:
            mint = testTback
    tback = maxt
    tsgIndex = stepsPerOrbit + i - tback
    Kt = indexInterp(K, tsgIndex, 0)
    tstate = indexInterp(t_hist, tsgIndex, 0);
    unext = -Kt@np.hstack([cx-tstate[0,:], cv-tstate[1,:]])
    if norm(unext)>.5:
        unext = unext * (.5/norm(unext))

   ######### Propagation ###########
    tx = t_hist[stepsPerOrbit+i+1,0,:]
    tv = t_hist[stepsPerOrbit+i+1,1,:]
    cx,cv = ECIprop(cx, cv, step, accel=unext)
print("Total Sim Orbits Used: ", totalsimorbits)    
fig, ((ax1, ax2, ax3), (ax4, ax5, ax6)) = plt.subplots(2, 3, figsize=(8,4))
ax1.plot(t_hist[:, 0, 0], t_hist[:, 0, 1])
rainbow_plot(ax1, c_hist[:, 0, 0], c_hist[:, 0, 1])
rainbow_plot(ax2, c_hist_ric[:, 0, 0], c_hist_ric[:, 0, 1])
#rainbow_plot(ax3, range(steps), norm(c_hist_ric[:, 0, :], axis=1))
#ax3.text(len(c_hist_ric)-75,  norm(c_hist_ric[-1, 0, :])+50, "Final Norm="+str(int(norm(c_hist_ric[-1, 0, :])*10)/10))
rainbow_plot(ax3, umaghist)
rainbow_plot(ax4, range(steps), coneconsthist)
#ax4.text(float(steps*.2),  min(coneconsthist)+.2*(max(coneconsthist)-min(coneconsthist)), "max const="+str(float(np.max(coneconsthist)*1000)/1000))
#To be used when its actually getting close enough lol
rainbow_plot(ax5, range(steps), speedconsthist)
#ax5.text(steps*.2,  min(speedconsthist)+.2*(max(speedconsthist)-min(speedconsthist)), "max const="+str(float(np.max(speedconsthist)*1000)/1000))
rainbow_plot(ax6, tbackhist)
plt.show()