# -*- coding: utf-8 -*-
"""Orbital Modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZcmpaAbdeYN4EzFzLB6vcj7VW300nRP

TODO:


*   Merge files with desktop version
*   Keep lowering loss
*   Make sure test is working as expected
*   Fix state norms for magnitude of target (shouldn't rely on floating point error')

Long Term (keep list for thesis)

* Train on data in relative coordinates maybe with a target radius value
*   Obvious easy change: cap binary search with LSTM bad guess
*   No time dependance
"""
#%% Imports and Fcns
#imports
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from numpy.linalg import norm
import sys
import h5py
import itertools
from scipy.signal import cont2discrete
from scipy.linalg import solve_discrete_are

#System Variables required for Target/LQR calc
mu = 398600.4418 #km^3/s^2
a_target = 7000 #km
n=np.sqrt(mu/a_target**3)
T_target = 2*np.pi*np.sqrt(a_target**3/mu)
step = 1 #seconds
kx = 10 #From paper, required for K calc
kv = 1
ku = 1
Q = np.block([[kx*np.eye(3), np.zeros((3,3))],[np.zeros((3,3)), kv*np.eye(3)]])
R = ku*np.eye(3)
conehalfangle = 20*np.pi/180 #half angle in radians the chaser must stay within.
g1=5 #km when constraint kicks in
g2=20 #Paper says rad/sec, I think its (km/s)/km
g3=0.001 #km/sec speed limit at dist 0.

def rainbow_plot2(ax, x, y, linewidth=2, **kwargs):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)

    if len(x) != len(y):
        raise ValueError("x and y must have the same length.")
    if len(x) < 2:
        raise ValueError("At least 2 points are required to draw a line.")

    # Rainbow spans hue 0.0 (red) → ~0.83 (purple/violet) in HSV space
    hues = np.linspace(0.0, 0.83, len(x) - 1)

    for i, hue in enumerate(hues):
        color = mcolors.hsv_to_rgb([hue, 1.0, 1.0])
        ax.plot(
            [x[i], x[i + 1]],
            [y[i], y[i + 1]],
            color=color,
            linewidth=linewidth,
            **kwargs,
        )
def rainbow_plot(ax, x=[], y=[]):
    if len(x)!=0 and len(y)!=0:
      rainbow_plot2(ax, x, y)
    else:
      rainbow_plot2(ax, range(len(x)), x)

def ECIprop(pos, vel, step, accel=None):
    if accel is None:
        accel = np.zeros((3,1))
    accel = np.asarray(accel).reshape(3,)

    halfvel = vel + (0.5*(-mu*pos*step/norm(pos)**3)) + .5*accel*step
    newpos = pos + (halfvel*step)
    newvel = halfvel + (.5*(-mu*newpos*step/norm(newpos)**3)) + .5*accel*step
    return newpos, newvel
def gravity_gradient(pos):
    pmag = np.linalg.norm(pos)
    return (mu / pmag**5) * (3 * np.outer(pos, pos) - pmag**2 * np.eye(3))
def indexInterp(arr, dblIndex,axis):
    if dblIndex>np.size(arr, axis=axis):
        raise ValueError("Index must be less than array axis max index.")
    if dblIndex<0:
        raise ValueError("Index must non-negative")
    i = int(dblIndex)
    d = dblIndex - i
    j=i+1
    return ((1-d) * np.take(arr, i, axis=axis)) + ((d) * np.take(arr, j, axis=axis))
def ECI2RIC(pos, vel, eps=1e-10):
    if norm(pos) < eps or norm(vel) < eps:
        return np.eye(3)
    radial = pos / norm(pos)
    cross = np.cross(pos, vel)
    cross = cross / norm(cross)
    intrack = np.cross(cross, radial)
    return np.vstack((radial, intrack, cross))