# -*- coding: utf-8 -*-
"""Orbital Modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZcmpaAbdeYN4EzFzLB6vcj7VW300nRP

TODO:


*   Merge files with desktop version
*   Keep lowering loss
*   Make sure test is working as expected
*   Fix state norms for magnitude of target (shouldn't rely on floating point error')

Long Term (keep list for thesis)

* Train on data in relative coordinates maybe with a target radius value
*   Obvious easy change: cap binary search with LSTM bad guess
*   No time dependance
"""
#%% Imports and Fcns
#imports
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from numpy.linalg import norm
import sys
import h5py
import itertools

from scipy.signal import cont2discrete
from scipy.linalg import solve_discrete_are

def rainbow_plot2(ax, x, y, linewidth=2, **kwargs):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)

    if len(x) != len(y):
        raise ValueError("x and y must have the same length.")
    if len(x) < 2:
        raise ValueError("At least 2 points are required to draw a line.")

    # Rainbow spans hue 0.0 (red) → ~0.83 (purple/violet) in HSV space
    hues = np.linspace(0.0, 0.83, len(x) - 1)

    for i, hue in enumerate(hues):
        color = mcolors.hsv_to_rgb([hue, 1.0, 1.0])
        ax.plot(
            [x[i], x[i + 1]],
            [y[i], y[i + 1]],
            color=color,
            linewidth=linewidth,
            **kwargs,
        )
def rainbow_plot(ax, x=[], y=[]):
    if len(x)!=0 and len(y)!=0:
      rainbow_plot2(ax, x, y)
    else:
      rainbow_plot2(ax, range(len(x)), x)

def ECIprop(pos, vel, step, accel=None):
    if accel is None:
        accel = np.zeros((3,1))
    accel = np.asarray(accel).reshape(3,)

    halfvel = vel + (0.5*(-mu*pos*step/norm(pos)**3)) + .5*accel*step
    newpos = pos + (halfvel*step)
    newvel = halfvel + (.5*(-mu*newpos*step/norm(newpos)**3)) + .5*accel*step
    return newpos, newvel
def gravity_gradient(pos):
    pmag = np.linalg.norm(pos)
    return (mu / pmag**5) * (3 * np.outer(pos, pos) - pmag**2 * np.eye(3))
def indexInterp(arr, dblIndex,axis):
    if dblIndex>np.size(arr, axis=axis):
        raise ValueError("Index must be less than array axis max index.")
    if dblIndex<0:
        raise ValueError("Index must non-negative")
    i = int(dblIndex)
    d = dblIndex - i
    j=i+1
    return ((1-d) * np.take(arr, i, axis=axis)) + ((d) * np.take(arr, j, axis=axis))
def ECI2RIC(pos, vel, eps=1e-10):
    if norm(pos) < eps or norm(vel) < eps:
        return np.eye(3)
    radial = pos / norm(pos)
    cross = np.cross(pos, vel)
    cross = cross / norm(cross)
    intrack = np.cross(cross, radial)
    return np.vstack((radial, intrack, cross))

#%% Pre-calculating target and LQR gains
#---------------------------------------------

#System Variables required for Target/LQR calc
mu = 398600.4418 #km^3/s^2
a_target = 7000 #km
n=np.sqrt(mu/a_target**3)
T_target = 2*np.pi*np.sqrt(a_target**3/mu)
step = 1 #seconds
kx = 10 #From paper, required for K calc
kv = 1
ku = 1
Q = np.block([[kx*np.eye(3), np.zeros((3,3))],[np.zeros((3,3)), kv*np.eye(3)]])
R = ku*np.eye(3)
conehalfangle = 20*np.pi/180 #half angle in radians the chaser must stay within.
g1=5 #km when constraint kicks in
g2=20 #Paper says rad/sec, I think its (km/s)/km
g3=0.001 #km/sec speed limit at dist 0.
tx0 = np.array([a_target,0,0])
tv0 = np.array([0,np.sqrt(mu/norm(tx0)),0])

tx=tx0.copy()
tv=tv0.copy()
#Compute n orbits of gains and target states
n=3

stepsPerOrbit = int(T_target//step)
t_hist = np.zeros((n*stepsPerOrbit,2,3))
K = np.zeros((n*stepsPerOrbit,3,6))
B_cont = np.block([[np.zeros((3,3))],[np.eye((3))]])
minDist = np.inf
tback0 = 0
print("-"*int(2+np.floor((n*stepsPerOrbit)/1000)))
for i in range(n*stepsPerOrbit):
    if i%1000 == 0:
      print("-", end="")
    t_hist[i,0,:] = tx
    t_hist[i,1,:] = tv
    g = gravity_gradient(tx)
    A_cont = np.block([[np.zeros((3,3)), np.eye(3)],[g, np.zeros((3,3))]])
    discreteTuple = cont2discrete((A_cont, B_cont, np.eye(6), np.zeros((6,3))), step)
    A_disc = discreteTuple[0]
    B_disc = discreteTuple[1]
    St=solve_discrete_are(A_disc, B_disc, Q, R)
    Kt=np.linalg.inv(B_disc.T @ St @ B_disc) @ B_disc.T @ St @ A_disc
    K[i,:] = Kt
    #Used in initial TSG value
    tx,tv = ECIprop(tx, tv, step)
print("-", end="")

#%% Single Run with plotting and bifrication only
#----------------------------------------------

initAngle = .15 #neg in track
amultchaser = 1.001 #SMA ratio chaser/target
zoffset = 0
orbits = .025
total_sim_orbits = 0

cx0 = np.array([amultchaser*a_target*np.cos(-initAngle),amultchaser*a_target*np.sin(-initAngle),zoffset])
cv0mag = np.sqrt(mu/norm(cx0))
cv0 = np.array([-cv0mag*np.sin(-initAngle),cv0mag*np.cos(-initAngle),0])
unext = np.zeros((3,1)) #First Timestep, just use zero accel

initdists = norm(t_hist[0:stepsPerOrbit,0,:]-cx0,axis=1)
tback0 = stepsPerOrbit - np.argmin(initdists) + 1

#Initialize states for this run
tx=t_hist[stepsPerOrbit,0,:]
tv=t_hist[stepsPerOrbit,1,:]
cx=cx0.copy()
cv=cv0.copy()
tback=tback0

steps = int(orbits*T_target)//step
#At time 0, tx is at t_hist[stepsperorbit]
if np.size(t_hist,axis=0) < (2*stepsPerOrbit)+steps:
    raise ValueError("Need longer precompute")

#Initialize lists for plotting
c_hist = np.zeros((steps,2,3)) # Shape (n, 2, 3)
c_hist_ric = np.zeros((steps,2,3))
tenergyhist = np.zeros((steps,1)) # Shape (n,)
umaghist = np.zeros((steps,1)) # Shape (n,)
coneconsthist = np.zeros((steps,1)) # Shape (n,)
speedconsthist = np.zeros((steps,1)) # Shape (n,)
tbackhist = np.zeros((steps,1)) # Shape (n,)
#print("-"*(1+(steps//10)))
for i in range(steps):
  ######### Logging ###########
    c_hist[i,0,:] = cx
    #c_hist[i,1,:] = cv
    Tmat = ECI2RIC(tx, tv)
    c_hist_ric[i,0,:] = Tmat @ (cx-tx)
    c_hist_ric[i,1,:] = Tmat @ (cv-tv)
    #tenergyhist[i] = 0.5*norm(tv)**2 - (mu/norm(tx))
    umaghist[i] = norm(unext)
    coneconsthist[i] = -1*(( -tv.T @ (cx-tx)/norm(cx-tx)) / (norm(tv))) + np.cos(conehalfangle) if norm(cx-tx)>1e-3 else 0
    speedconsthist[i] = norm(cv-tv) - (g2*norm(cx-tx)) - g3 if norm(cx-tx) <= g1 and norm(cx-tx)>1e-3 else 0
    tbackhist[i] = tback
  ######### Control Calc ###########
    mint = 0.0001 #s
    maxt = tback #from last propagation
    if tback > 2:
        thresh = .5
    elif tback < 2:
        thresh = .01
    elif tback < .5:
        thresh = 0
        maxt = 0
    while maxt - mint > thresh:
        test = (maxt+mint)/2
        txsim = tx.copy()
        tvsim = tv.copy()
        cxsim = cx.copy()
        cvsim = cv.copy()
        total_sim_orbits += 1
        for j in range(i,i+stepsPerOrbit):
            speedconst = norm(cvsim-tvsim) - (g2*norm(cxsim-txsim)) - g3 if norm(cxsim-txsim) <= g1  and norm(cxsim-txsim)>1e-3 else 0
            normedpos = (cxsim-txsim)/norm(cxsim-txsim)
            coneconst = -1*(( -tvsim.T @ normedpos) / (norm(tvsim))) + np.cos(conehalfangle) if norm(cxsim-txsim)>1e-3 else 0
            if speedconst > 0 or coneconst > 0:
                if j==i:
                    raise ValueError("Error, const already broken shouldnt be possible")
                break
            tsgIndex = stepsPerOrbit + j - test
            Kt = indexInterp(K, tsgIndex, 0)
            tstate = indexInterp(t_hist, tsgIndex, 0);
            unext = -Kt@np.hstack([cxsim-tstate[0,:], cvsim-tstate[1,:]])
            if norm(unext)>.5:
                unext = unext * (.5/norm(unext))
            txsim = t_hist[stepsPerOrbit+j+1,0,:]
            tvsim = t_hist[stepsPerOrbit+j+1,1,:]
            cxsim,cvsim = ECIprop(cxsim, cvsim, step, accel=unext)
        if j == i + stepsPerOrbit - 1:
            maxt = test #consts met
        else:
            mint = test
    tback = maxt
    tsgIndex = stepsPerOrbit + i - tback
    Kt = indexInterp(K, tsgIndex, 0)
    tstate = indexInterp(t_hist, tsgIndex, 0);
    unext = -Kt@np.hstack([cx-tstate[0,:], cv-tstate[1,:]])
    if norm(unext)>.5:
        unext = unext * (.5/norm(unext))


   ######### Propagation ###########
    tx = t_hist[stepsPerOrbit+i+1,0,:]
    tv = t_hist[stepsPerOrbit+i+1,1,:]
    cx,cv = ECIprop(cx, cv, step, accel=unext)
print("Total Simulated Orbits = ", total_sim_orbits)
fig, ((ax1, ax2, ax3), (ax4, ax5, ax6)) = plt.subplots(2, 3, figsize=(8,4))
ax1.plot(t_hist[:, 0, 0], t_hist[:, 0, 1])
rainbow_plot(ax1, c_hist[:, 0, 0], c_hist[:, 0, 1])
rainbow_plot(ax2, c_hist_ric[:, 0, 0], c_hist_ric[:, 0, 1])
#rainbow_plot(ax3, range(steps), norm(c_hist_ric[:, 0, :], axis=1))
#ax3.text(len(c_hist_ric)-75,  norm(c_hist_ric[-1, 0, :])+50, "Final Norm="+str(int(norm(c_hist_ric[-1, 0, :])*10)/10))
rainbow_plot(ax3, umaghist)
rainbow_plot(ax4, range(steps), coneconsthist)
ax4.text(float(steps*.2),  min(coneconsthist)+.2*(max(coneconsthist)-min(coneconsthist)), "max const="+str(int(max(coneconsthist)*1000)/1000))
#To be used when its actually getting close enough lol
rainbow_plot(ax5, range(steps), speedconsthist)
ax5.text(steps*.2,  min(speedconsthist)+.2*(max(speedconsthist)-min(speedconsthist)), "max const="+str(int(max(speedconsthist)*1000)/1000))
rainbow_plot(ax6, tbackhist)
plt.show()
#%% Data file gen

initAngles = np.linspace(0.1, 0.3, 10)
amultchasers = np.linspace(0.997, 1.003, 10)
zoffsets = np.linspace(-5, 5, 5)
initvars = list(itertools.product(initAngles, amultchasers, zoffsets))
orbits = .05

filepath = 'big2.h5'
with h5py.File(filepath, 'w') as h5file:
    for scenario_num, (initAngle, amultchaser, zoffset) in enumerate(initvars):
      print(scenario_num,"/",len(initvars))
      cx0 = np.array([amultchaser*a_target*np.cos(-initAngle),amultchaser*a_target*np.sin(-initAngle),zoffset])
      cv0mag = np.sqrt(mu/norm(cx0))
      cv0 = np.array([-cv0mag*np.sin(-initAngle),cv0mag*np.cos(-initAngle),0])
      unext = np.zeros((3,1)) #First Timestep, just use zero accel
    
      initdists = norm(t_hist[0:stepsPerOrbit,0,:]-cx0,axis=1)
      tback0 = stepsPerOrbit - np.argmin(initdists) + 1
    
      #Initialize states for this run
      tx=t_hist[stepsPerOrbit,0,:]
      tv=t_hist[stepsPerOrbit,1,:]
      cx=cx0.copy()
      cv=cv0.copy()
      tback=tback0
    
      steps = int(orbits*T_target)//step
      #At time 0, tx is at t_hist[stepsperorbit]
      if np.size(t_hist,axis=0) < (2*stepsPerOrbit)+steps:
          raise ValueError("Need longer precompute")
    
      #Initialize lists for plotting
      c_hist = np.zeros((steps,2,3)) # Shape (n, 2, 3)
      c_hist_ric = np.zeros((steps,2,3))
      tbackhist = np.zeros((steps,1)) # Shape (n,)
      #print("-"*(1+(steps//10)))
      for i in range(steps):
        ######### Logging ###########
          c_hist[i,0,:] = cx
          c_hist[i,1,:] = cv
          Tmat = ECI2RIC(tx, tv)
          c_hist_ric[i,0,:] = Tmat @ (cx-tx)
          c_hist_ric[i,1,:] = Tmat @ (cv-tv)
          coneconst = -1*(( -tv.T @ (cx-tx)/norm(cx-tx)) / (norm(tv))) + np.cos(conehalfangle) if norm(cx-tx)>1e-3 else 0
          speedconst = norm(cv-tv) - (g2*norm(cx-tx)) - g3 if norm(cx-tx) <= g1 and norm(cx-tx)>1e-3 else 0
          if coneconst > 0 or speedconst >0:
              raise ValueError("Scenario broke constraints. (initAngle, amultchaser, zoffset) = ("+str(initAngle) +" "+ str(amultchaser) +" "+ str(zoffset) +")")
          tbackhist[i] = tback
        ######### Control Calc ###########
          mint = 0.0001 #s
          maxt = tback #from last propagation
          if tback > 2:
              thresh = .5
          elif tback < 2:
              thresh = .01
          elif tback < .5:
              thresh = 0
              maxt = 0
          while maxt - mint > thresh:
              test = (maxt+mint)/2
              txsim = tx.copy()
              tvsim = tv.copy()
              cxsim = cx.copy()
              cvsim = cv.copy()
              for j in range(i,i+stepsPerOrbit):
                  speedconst = norm(cvsim-tvsim) - (g2*norm(cxsim-txsim)) - g3 if norm(cxsim-txsim) <= g1  and norm(cxsim-txsim)>1e-3 else 0
                  normedpos = (cxsim-txsim)/norm(cxsim-txsim)
                  coneconst = -1*(( -tvsim.T @ normedpos) / (norm(tvsim))) + np.cos(conehalfangle) if norm(cxsim-txsim)>1e-3 else 0
                  if speedconst > 0 or coneconst > 0:
                      if j==i:
                          raise ValueError("Error, const already broken shouldnt be possible")
                      break
                  tsgIndex = stepsPerOrbit + j - test
                  Kt = indexInterp(K, tsgIndex, 0)
                  tstate = indexInterp(t_hist, tsgIndex, 0);
                  unext = -Kt@np.hstack([cxsim-tstate[0,:], cvsim-tstate[1,:]])
                  if norm(unext)>.5:
                      unext = unext * (.5/norm(unext))
                  txsim = t_hist[stepsPerOrbit+j+1,0,:]
                  tvsim = t_hist[stepsPerOrbit+j+1,1,:]
                  cxsim,cvsim = ECIprop(cxsim, cvsim, step, accel=unext)
              if j == i + stepsPerOrbit - 1:
                  maxt = test #consts met
              else:
                  mint = test
          tback = maxt
          tsgIndex = stepsPerOrbit + i - tback
          Kt = indexInterp(K, tsgIndex, 0)
          tstate = indexInterp(t_hist, tsgIndex, 0);
          unext = -Kt@np.hstack([cx-tstate[0,:], cv-tstate[1,:]])
          if norm(unext)>.5:
              unext = unext * (.5/norm(unext))
    
    
          ######### Propagation ###########
          tx = t_hist[stepsPerOrbit+i+1,0,:]
          tv = t_hist[stepsPerOrbit+i+1,1,:]
          cx,cv = ECIprop(cx, cv, step, accel=unext)
      grp = h5file.create_group(f'scenario_{scenario_num:03d}')
      grp.create_dataset('chaser_pos', data=c_hist[:, 0, :])
      grp.create_dataset('chaser_vel', data=c_hist[:, 1, :])
      grp.create_dataset('target_pos', data=t_hist[stepsPerOrbit:stepsPerOrbit+steps, 0, :])
      grp.create_dataset('target_vel', data=t_hist[stepsPerOrbit:stepsPerOrbit+steps, 1, :])
      grp.create_dataset('tback', data=tbackhist)
      grp.create_dataset('chaser_pos_ric', data=c_hist_ric[:, 0, :])
      grp.create_dataset('chaser_vel_ric', data=c_hist_ric[:, 1, :])
      grp.attrs['initAngle'] = initAngle
      grp.attrs['amultchaser'] = amultchaser
      grp.attrs['zoffset'] = zoffset
      grp.attrs['tback0'] = float(tback0)
#%% tback norm calcs
import matplotlib
matplotlib.use('tkAgg')
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.utils.data import random_split
import h5py
import matplotlib.pyplot as plt
torch.manual_seed(1)

class NormDataset(Dataset):
    def __init__(self, hdf5_path):
        self.hdf5_path = hdf5_path
        with h5py.File(hdf5_path, 'r') as f:
            self.sequences = [k for k in sorted(f.keys()) if k.startswith('scenario_')]

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        with h5py.File(self.hdf5_path, 'r') as f:
            g = f[self.sequences[idx]]
            tback      = torch.FloatTensor(g['tback'][:])
            target_pos = torch.FloatTensor(g['target_pos'][:])
            chaser_pos = torch.FloatTensor(g['chaser_pos'][:])
            chaser_vel = torch.FloatTensor(g['chaser_vel'][:])
            target_vel = torch.FloatTensor(g['target_vel'][:])
            pos_ric    = torch.FloatTensor(g['chaser_pos_ric'][:])
            vel_ric    = torch.FloatTensor(g['chaser_vel_ric'][:])

        mag         = torch.norm(target_pos, dim=1, keepdim=True)
        state_local = torch.cat([pos_ric, vel_ric, mag], dim=1)
        state_abs   = torch.cat([chaser_pos, target_pos, chaser_vel, target_vel], dim=1)
        return state_local, state_abs, tback


dataset = NormDataset('./big2.h5')
loader  = DataLoader(dataset, batch_size=1, shuffle=False)

tback_min, tback_max = float('inf'), float('-inf')
mins = {'local': torch.full((7,), float('inf')),  'abs': torch.full((12,), float('inf'))}
maxs = {'local': torch.full((7,), float('-inf')), 'abs': torch.full((12,), float('-inf'))}

for c, (s_loc, s_abs, tback) in enumerate(loader):
    s_loc, s_abs, tback = s_loc.squeeze(0), s_abs.squeeze(0), tback.squeeze(0)
    tback_min = min(tback_min, tback.min().item())
    tback_max = max(tback_max, tback.max().item())
    for key, s in [('local', s_loc), ('abs', s_abs)]:
        mins[key] = torch.minimum(mins[key], s.min(dim=0).values)
        maxs[key] = torch.maximum(maxs[key], s.max(dim=0).values)
    if (c + 1) % 5 == 0:
        print(f"Scenario {c+1}/{len(dataset)}")

torch.save({'tback_min': torch.tensor(tback_min), 'tback_max': torch.tensor(tback_max),
            'state_min_loc': mins['local'], 'state_max_loc': maxs['local'],
            'state_min_abs': mins['abs'],   'state_max_abs': maxs['abs']}, 'norm.pth')

#%% NN Imports and definitions
import matplotlib
matplotlib.use('tkAgg')
import numpy as np
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from torch.utils.data import random_split
import h5py
import matplotlib.pyplot as plt
import time
from IPython.display import display
import h5py
import itertools
torch.manual_seed(time.time())

class ScenarioDataset(Dataset):
    def __init__(self, hdf5_path, sequence_length=1, local=False):
        self.hdf5_path = hdf5_path
        self.sequence_length = sequence_length
        self.local = local
        self.sequences = []
        self.start_steps = []
        self.cutoffs = {}
        
        with h5py.File(hdf5_path, 'r') as f:
            for key in sorted(f.keys()):
                if key.startswith('scenario_'):
                    pos_ric = torch.FloatTensor(f[key]['chaser_pos_ric'][:])
                    norms = torch.norm(pos_ric, dim=1)
                    diffs = norms[1:] - norms[:-1]
                    cutoff = (diffs > 0).nonzero()
                    cutoff = cutoff[0].item() + 6 if len(cutoff) > 0 else len(norms)
                    self.cutoffs[key] = cutoff
                    num_steps = len(f[key]['chaser_pos'])
                    max_start = num_steps - sequence_length
                    for start_idx in range(min(cutoff, max_start)):
                        self.sequences.append(key)
                        self.start_steps.append(start_idx)
        
        state_type = "local (7D)" if local else "absolute (12D)"
        print(f"Dataset: {len(self)} samples, sequence_length={sequence_length}, state={state_type}")
    
    def __len__(self):
        return len(self.sequences)
    
    def __getitem__(self, idx):
        scenario_key = self.sequences[idx]
        start_step = self.start_steps[idx]
        end_step = start_step + self.sequence_length
        
        with h5py.File(self.hdf5_path, 'r') as f:
            group = f[scenario_key]
            
            
            tback = torch.FloatTensor(group['tback'][start_step:end_step])
            target_pos = torch.FloatTensor(group['target_pos'][start_step:end_step])
            
            if self.local:
                # Relative coordinates: (seq_len, 3)
                chaser_eci_pos = torch.FloatTensor(group['chaser_pos_ric'][start_step:end_step])
                chaser_eci_vel = torch.FloatTensor(group['chaser_vel_ric'][start_step:end_step])
                
                # Magnitude of target position: (seq_len, 1)
                target_mag = torch.norm(target_pos, dim=1, keepdim=True)
                
                # Stack: (seq_len, 7)
                state = torch.cat([chaser_eci_pos, chaser_eci_vel, target_mag], dim=1)
            else:
                # Extract sequence
                chaser_pos = torch.FloatTensor(group['chaser_pos'][start_step:end_step])
                chaser_vel = torch.FloatTensor(group['chaser_vel'][start_step:end_step])
                target_vel = torch.FloatTensor(group['target_vel'][start_step:end_step])
                # Absolute coordinates: (seq_len, 12)
                state = torch.cat([chaser_pos, target_pos, chaser_vel, target_vel], dim=1)
            
            # Squeeze if sequence length is 1
            if self.sequence_length == 1:
                state = state.squeeze(0)  # (7,) or (12,)
                tback = tback.squeeze(0)  # (1,)
        
        return state, tback
class FromSequenceModel(nn.Module):
    #needs updates with normalizaitons
    def __init__(self, input_size=12, hidden_size=64, num_layers=2):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)
    
    def forward(self, x):
        # x shape: (batch, steps, 12)
        lstm_out, _ = self.lstm(x)  # (batch, steps, hidden_size)
        output = self.fc(lstm_out)   # (batch, steps, 1)
        return output  
class FromStateModel(nn.Module):
    def __init__(self, input_size=12, hidden_size=64, num_hidden_layers=3):
        super().__init__()
        self.relu = nn.LeakyReLU()
        self.sig = nn.Sigmoid()
        
        layers = [nn.Linear(input_size, hidden_size)]
        for _ in range(num_hidden_layers - 1):
            layers.append(nn.Linear(hidden_size, hidden_size))
        self.hidden_layers = nn.ModuleList(layers)
        self.output_layer = nn.Linear(hidden_size, 1)
    
    def forward(self, x):
        for layer in self.hidden_layers:
            x = self.relu(layer(x))
        return self.sig(self.output_layer(x))
class NotTooLowLoss(nn.Module):
    def __init__(self, nu = 0):
        super().__init__()
        self.nu = nu
        self.relu = nn.ReLU()
    
    def forward(self, predictions, targets):
        # Your loss computation here
        error = predictions - targets
        loss = error**2
        reluloss = self.relu(-error)**2
        return (loss.sum() + (self.nu * reluloss.sum())) / loss.numel()
#%% NN Training
blnPlot = False
if blnPlot:
    plt.ioff()
    fig, ax = plt.subplots()
    train_losses, val_losses = [], []  
    ax.set_ylabel('Loss')
    plt.show(block=False)
  
#Hyperparameters
seqLength = 1
localState = True
#val_perc = .1
val_size = 1500
batch_size = 2 ** 9
# hidden_size = 2 ** 11
# num_hidden_layers = 8
learning_rate = .0005
hidden_sizes = [2**10, 2 ** 11]
num_hidden_layerss = [6, 7 ,8, 9]
tooLowPenalty = .01
withSched = True
nepochs = 30
from contextlib import redirect_stdout
with open("june4sweep.txt", "w") as f:
    for (hidden_size, num_hidden_layers) in itertools.product(hidden_sizes, num_hidden_layerss):
        print(hidden_size, num_hidden_layers, withSched, file=f)
        # Training
        if localState:
            dims = 7
        else:
            dims = 12
        dataset = ScenarioDataset('./big2.h5',sequence_length=seqLength,local=localState)
        total_size = len(dataset)
        train_size = int(0.6 * total_size)
        #val_size = int(val_perc * total_size)
        test_size = total_size - train_size - val_size
        
        train_dataset, val_dataset, test_dataset = random_split(
            dataset, [train_size, val_size, test_size])
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=True)
        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True)
        
        normFromFile = torch.load('norm.pth', weights_only=True)
        tback_min = normFromFile['tback_min']
        tback_max = normFromFile['tback_max']
        state_min = normFromFile['state_min_loc'] if localState else normFromFile['state_min_abs']
        state_max = normFromFile['state_max_loc'] if localState else normFromFile['state_max_abs']
        state_range = torch.tensor([ma - mi if torch.abs(ma - mi) > 1e-3 else np.inf
                                     for ma, mi in zip(state_max, state_min)])
        
        
        if seqLength == 1:
            model = FromStateModel(input_size=dims, hidden_size=hidden_size)
        else:
            model = FromSequenceModel(input_size=dims, hidden_size=hidden_size, num_layers=seqLength)
        optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
        criterion = NotTooLowLoss(tooLowPenalty)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=30, factor=0.5)
        
        min_val_loss=np.inf
        update = False
        model_path = time.strftime('model_%b%d_%H%M.pth')
        print(f"Model Saving as: {model_path}", file=f)
        print(f"{len(train_loader)} Batches Per Epoch", file=f)
        print(f"{train_loader.batch_size} Samples per Batch", file=f)
        try:
            for epoch in range(nepochs):
                # Training
                train_loss = 0
                for batchidx, (state, tback) in enumerate(train_loader):
                    state = (state - state_min) / state_range
                    optimizer.zero_grad()
                    outputs = model(state)
                    tback_norm = (tback - tback_min) / (tback_max - tback_min)
                    loss = criterion(outputs, tback_norm)
                    loss.backward()
                    optimizer.step()
                    train_loss = (batchidx/(batchidx+1))*train_loss + (loss.item() / (batchidx+1))
                    
                     # Validate every N batches
                    if (batchidx + 1) % 5 == 0:
                        val_loss = 0
                        with torch.no_grad():
                            for state_val, tback_val in val_loader:
                                state_val = (state_val - state_min) / state_range
                                outputs_val = model(state_val)
                                tback_val_norm = (tback_val - tback_min) / (tback_max - tback_min)
                                loss_val = criterion(outputs_val, tback_val_norm)
                                val_loss += loss_val.item()
                        val_loss /= len(val_loader)
                        scheduler.step(val_loss)
                        if val_loss < min_val_loss:
                            min_val_loss = val_loss
                            torch.save({'model': model.state_dict(), 'tback_min': tback_min, 'tback_max': tback_max}, model_path)
                            print(f"Epoch {epoch+1}, Batch {batchidx+1} | Train: {np.sqrt(loss.item()):.4f}, Val: {np.sqrt(val_loss):.4f} | LR: {optimizer.param_groups[0]['lr']:.2e} saved", file=f)
                        else:
                            print(f"Epoch {epoch+1}, Batch {batchidx+1} | Train: {np.sqrt(loss.item()):.4f}, Val: {np.sqrt(val_loss):.4f} | LR: {optimizer.param_groups[0]['lr']:.2e}", file=f)
                        if blnPlot:
                            train_losses.append(train_loss)
                            val_losses.append(val_loss)
                            ax.clear()
                            ax.plot(range(len(train_losses)), train_losses, label='Train', alpha=0.7)
                            ax.plot(range(len(train_losses)), val_losses, label='Val', alpha=0.7)
                            ax.legend()
                            ax.set_ylabel('Loss')
                            fig.show()
                            #plt.pause(.05)
                            fig.canvas.flush_events()
        except:
            plt.close()    
            plt.pause(.1)    
            plt.switch_backend('module://matplotlib_inline.backend_inline')
            display(fig)
            print(f"Model Saved as: {model_path}")
            sys.exit()
        # Test on holdout set
        print("\nTesting...", file=f)
        #model.load_state_dict(torch.load(model_path))
        model.eval()
        
        test_loss = 0
        all_preds = []
        all_actuals = []
        
        with torch.no_grad():
            for state, tback in test_loader:
                state = (state - state_min) / state_range
                outputs = model(state)
                loss = criterion(outputs, tback)
                test_loss += loss.item()
        
        test_loss /= len(test_loader)
        print(f"Test Loss: {test_loss:.4f}", file=f)

#%%
import time
# Load model
# dims = 7
# hidden_size = 1024
# localState=True

checkpoint = torch.load('model_Jun04_2247.pth', weights_only=False)
state_dict = checkpoint['model']

# Infer architecture from weights
input_layer_key = next(k for k in state_dict if 'weight' in k)
dims = state_dict[input_layer_key].shape[1]
localState = True if dims == 7 else False
hidden_size = state_dict[input_layer_key].shape[0]
num_layers = sum([1 for k in state_dict if k.endswith('.weight') and 'out' not in k])

bestmodel = FromStateModel(input_size=dims, hidden_size=hidden_size, num_hidden_layers=num_layers)
bestmodel.load_state_dict(state_dict)
bestmodel.eval()

# checkpoint = torch.load('model_Jun04_2334.pth', weights_only=False)
# bestmodel = FromStateModel(input_size=dims, hidden_size=hidden_size, num_hidden_layers=num_hidden_layers)
# bestmodel.load_state_dict(checkpoint['model'])
# bestmodel.eval()
normFromFile = torch.load('norm.pth', weights_only=True)
tback_min = normFromFile['tback_min']
tback_max = normFromFile['tback_max']
state_min = normFromFile['state_min_loc'] if localState else normFromFile['state_min_abs']
state_max = normFromFile['state_max_loc'] if localState else normFromFile['state_max_abs']


# Get some test samples
dataset_test = ScenarioDataset('big2.h5', sequence_length=1, local=localState)
torch.manual_seed(time.time())
dataloader_test = DataLoader(dataset_test, batch_size=5, shuffle=True)

with torch.no_grad():
    for state, actual_tback in dataloader_test:
        state = (state - state_min) / (state_max - state_min)
        predicted_tback = bestmodel(state)
        predicted_tback_denorm = predicted_tback * (tback_max - tback_min) + tback_min
        print(predicted_tback)
        print(state)
        print("Sample | Actual tback | Predicted tback | Error")
        print("-" * 70)
        
        for i in range(state.shape[0]):
            state_sample = state[i, :3]  # First 3 dimensions
            actual = actual_tback[i].item()
            predicted = predicted_tback_denorm[i].item()
            error = abs(actual - predicted)
            print(f"{i+1:6d} | {actual:11.4f} | {predicted:15.4f} | {error:6.4f}")
        
        break  # Just show first batch
#%% Single Run with model and bifrication
#----------------------------------------------

initAngle = .15 #neg in track
amultchaser = 1.001 #SMA ratio chaser/target
zoffset = 0
orbits = .025
total_sim_orbits = 0

cx0 = np.array([amultchaser*a_target*np.cos(-initAngle),amultchaser*a_target*np.sin(-initAngle),zoffset])
cv0mag = np.sqrt(mu/norm(cx0))
cv0 = np.array([-cv0mag*np.sin(-initAngle),cv0mag*np.cos(-initAngle),0])
unext = np.zeros((3,1)) #First Timestep, just use zero accel

initdists = norm(t_hist[0:stepsPerOrbit,0,:]-cx0,axis=1)
tback0 = stepsPerOrbit - np.argmin(initdists) + 1

#Initialize states for this run
tx=t_hist[stepsPerOrbit,0,:]
tv=t_hist[stepsPerOrbit,1,:]
cx=cx0.copy()
cv=cv0.copy()
tback=tback0

steps = int(orbits*T_target)//step
#At time 0, tx is at t_hist[stepsperorbit]
if np.size(t_hist,axis=0) < (2*stepsPerOrbit)+steps:
    raise ValueError("Need longer precompute")

#Initialize lists for plotting
c_hist = np.zeros((steps,2,3)) # Shape (n, 2, 3)
c_hist_ric = np.zeros((steps,2,3))
tenergyhist = np.zeros((steps,1)) # Shape (n,)
umaghist = np.zeros((steps,1)) # Shape (n,)
coneconsthist = np.zeros((steps,1)) # Shape (n,)
speedconsthist = np.zeros((steps,1)) # Shape (n,)
tbackhist = np.zeros((steps,1)) # Shape (n,)
#print("-"*(1+(steps//10)))
for i in range(steps):
  ######### Logging ###########
    c_hist[i,0,:] = cx
    #c_hist[i,1,:] = cv
    Tmat = ECI2RIC(tx, tv)
    c_hist_ric[i,0,:] = Tmat @ (cx-tx)
    c_hist_ric[i,1,:] = Tmat @ (cv-tv)
    #tenergyhist[i] = 0.5*norm(tv)**2 - (mu/norm(tx))
    umaghist[i] = norm(unext)
    coneconsthist[i] = -1*(( -tv.T @ (cx-tx)/norm(cx-tx)) / (norm(tv))) + np.cos(conehalfangle) if norm(cx-tx)>1e-3 else 0
    speedconsthist[i] = norm(cv-tv) - (g2*norm(cx-tx)) - g3 if norm(cx-tx) <= g1 and norm(cx-tx)>1e-3 else 0
    tbackhist[i] = tback
  ######### Control Calc ###########
    mint = 0.0001 #s
    maxt = tback #from last propagation
    if tback > 2:
        thresh = .5
    elif tback < 2:
        thresh = .01
    elif tback < .5:
        thresh = 0
        maxt = 0
    while maxt - mint > thresh:
        test = (maxt+mint)/2
        txsim = tx.copy()
        tvsim = tv.copy()
        cxsim = cx.copy()
        cvsim = cv.copy()
        total_sim_orbits += 1
        for j in range(i,i+stepsPerOrbit):
            speedconst = norm(cvsim-tvsim) - (g2*norm(cxsim-txsim)) - g3 if norm(cxsim-txsim) <= g1  and norm(cxsim-txsim)>1e-3 else 0
            normedpos = (cxsim-txsim)/norm(cxsim-txsim)
            coneconst = -1*(( -tvsim.T @ normedpos) / (norm(tvsim))) + np.cos(conehalfangle) if norm(cxsim-txsim)>1e-3 else 0
            if speedconst > 0 or coneconst > 0:
                if j==i:
                    raise ValueError("Error, const already broken shouldnt be possible")
                break
            tsgIndex = stepsPerOrbit + j - test
            Kt = indexInterp(K, tsgIndex, 0)
            tstate = indexInterp(t_hist, tsgIndex, 0);
            unext = -Kt@np.hstack([cxsim-tstate[0,:], cvsim-tstate[1,:]])
            if norm(unext)>.5:
                unext = unext * (.5/norm(unext))
            txsim = t_hist[stepsPerOrbit+j+1,0,:]
            tvsim = t_hist[stepsPerOrbit+j+1,1,:]
            cxsim,cvsim = ECIprop(cxsim, cvsim, step, accel=unext)
        if j == i + stepsPerOrbit - 1:
            maxt = test #consts met
        else:
            mint = test
    tback = maxt
    tsgIndex = stepsPerOrbit + i - tback
    Kt = indexInterp(K, tsgIndex, 0)
    tstate = indexInterp(t_hist, tsgIndex, 0);
    unext = -Kt@np.hstack([cx-tstate[0,:], cv-tstate[1,:]])
    if norm(unext)>.5:
        unext = unext * (.5/norm(unext))


   ######### Propagation ###########
    tx = t_hist[stepsPerOrbit+i+1,0,:]
    tv = t_hist[stepsPerOrbit+i+1,1,:]
    cx,cv = ECIprop(cx, cv, step, accel=unext)

print("total simulated orbits = ", total_sim_orbits)
fig, ((ax1, ax2, ax3), (ax4, ax5, ax6)) = plt.subplots(2, 3, figsize=(8,4))
ax1.plot(t_hist[:, 0, 0], t_hist[:, 0, 1])
rainbow_plot(ax1, c_hist[:, 0, 0], c_hist[:, 0, 1])
rainbow_plot(ax2, c_hist_ric[:, 0, 0], c_hist_ric[:, 0, 1])
#rainbow_plot(ax3, range(steps), norm(c_hist_ric[:, 0, :], axis=1))
#ax3.text(len(c_hist_ric)-75,  norm(c_hist_ric[-1, 0, :])+50, "Final Norm="+str(int(norm(c_hist_ric[-1, 0, :])*10)/10))
rainbow_plot(ax3, umaghist)
rainbow_plot(ax4, range(steps), coneconsthist)
ax4.text(float(steps*.2),  min(coneconsthist)+.2*(max(coneconsthist)-min(coneconsthist)), "max const="+str(int(max(coneconsthist)*1000)/1000))
#To be used when its actually getting close enough lol
rainbow_plot(ax5, range(steps), speedconsthist)
ax5.text(steps*.2,  min(speedconsthist)+.2*(max(speedconsthist)-min(speedconsthist)), "max const="+str(int(max(speedconsthist)*1000)/1000))
rainbow_plot(ax6, tbackhist)
plt.show()