# -*- coding: utf-8 -*-
"""Orbital Modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZcmpaAbdeYN4EzFzLB6vcj7VW300nRP

TODO:


*   Merge files with desktop version
*   Keep lowering loss
*   Make sure test is working as expected
*   Fix state norms for magnitude of target (shouldn't rely on floating point error')

Long Term (keep list for thesis)

* Train on data in relative coordinates maybe with a target radius value
*   Obvious easy change: cap binary search with LSTM bad guess
*   No time dependance
"""
import numpy as np
from numpy.linalg import norm
import h5py
import itertools
import os

from scipy.signal import cont2discrete
from scipy.linalg import solve_discrete_are
from globals import mu, indexInterp, ECI2RIC, ECIprop
from globals import gravity_gradient 
import time

a_target = 7000 #km
n=np.sqrt(mu/a_target**3)
T_target = 2*np.pi*np.sqrt(a_target**3/mu)
step = 1 #seconds
kx = 10 #From paper, required for K calc
kv = 1
ku = 1
Q = np.block([[kx*np.eye(3), np.zeros((3,3))],[np.zeros((3,3)), kv*np.eye(3)]])
R = ku*np.eye(3)
conehalfangle = 20*np.pi/180 #half angle in radians the chaser must stay within.
g1=5 #km when constraint kicks in
g2=20 #Paper says rad/sec, I think its (km/s)/km
g3=0.001 #km/sec speed limit at dist 0.

tx0 = np.array([a_target,0,0])
tv0 = np.array([0,np.sqrt(mu/norm(tx0)),0])

tx=tx0.copy()
tv=tv0.copy()
#Compute n orbits of gains and target states
n=3

stepsPerOrbit = int(T_target//step)


if os.path.exists("localsaves/precompute.npz"):
    with open("localsaves/precompute.npz","rb") as f:
        zvars = np.load(f)
        if zvars["a_target"] != a_target or zvars["step"] != step:
            raise ValueError('step size and a_target must match current script. a_target:'+
                             f' {a_target} != {zvars["a_target"]} or step: {step} != {zvars["step"]}')
        K = zvars["K"]
        t_hist = zvars["t_hist"]
        print("Loaded t_hist and K from file ./precompute.npz")
else: 
    t_hist = np.zeros((n*stepsPerOrbit,2,3))
    K = np.zeros((n*stepsPerOrbit,3,6))
    B_cont = np.block([[np.zeros((3,3))],[np.eye((3))]])
    print("Calculating precomputed t_hist and K values...")
    print("-"*int(2+np.floor((n*stepsPerOrbit)/1000)))
    for i in range(n*stepsPerOrbit):
        if i%1000 == 0:
          print("-", end="")
        t_hist[i,0,:] = tx
        t_hist[i,1,:] = tv
        g = gravity_gradient(tx)
        A_cont = np.block([[np.zeros((3,3)), np.eye(3)],[g, np.zeros((3,3))]])
        discreteTuple = cont2discrete((A_cont, B_cont, np.eye(6), np.zeros((6,3))), step)
        A_disc = discreteTuple[0]
        B_disc = discreteTuple[1]
        St=solve_discrete_are(A_disc, B_disc, Q, R)
        Kt=np.linalg.inv(B_disc.T @ St @ B_disc) @ B_disc.T @ St @ A_disc
        K[i,:] = Kt
        tx,tv = ECIprop(tx, tv, step)
    print("-", end="")
    if "thesis" in os.getcwd() or "Thesis" in os.getcwd():
        np.savez("localsaves/precompute.npz", K=K, t_hist=t_hist, a_target=a_target, step=step)

def OneOrbitNoLog(i0, cx0, cv0, testTback):
    cxsim = cx0.copy()
    cvsim = cv0.copy()
    txsim = t_hist[stepsPerOrbit+i0,0,:]
    tvsim = t_hist[stepsPerOrbit+i0,1,:]
    success = True
    for j in range(i0,i0+stepsPerOrbit):
        speedconst = norm(cvsim-tvsim) - (g2*norm(cxsim-txsim)) - g3 if norm(cxsim-txsim) <= g1  and norm(cxsim-txsim)>1e-3 else 0
        normedpos = (cxsim-txsim)/norm(cxsim-txsim)
        coneconst = -1*(( -tvsim.T @ normedpos) / (norm(tvsim))) + np.cos(conehalfangle) if norm(cxsim-txsim)>1e-3 else 0
        if speedconst > 0 or coneconst > 0:
            if j==i:
                raise ValueError("Error, const already broken shouldnt be possible")
            success = False
            break
        tsgIndex = stepsPerOrbit + j - testTback
        Kt = indexInterp(K, tsgIndex, 0)
        tstate = indexInterp(t_hist, tsgIndex, 0);
        unext = -Kt@np.hstack([cxsim-tstate[0,:], cvsim-tstate[1,:]])
        if norm(unext)>.5:
            unext = unext * (.5/norm(unext))
        txsim = t_hist[stepsPerOrbit+j+1,0,:]
        tvsim = t_hist[stepsPerOrbit+j+1,1,:]
        cxsim,cvsim = ECIprop(cxsim, cvsim, step, accel=unext)
    return success

initAngles = np.linspace(0.1, 0.3, 10)
amultchasers = np.linspace(0.997, 1.003, 10)
zoffsets = np.linspace(-5, 5, 5)
initvars = list(itertools.product(initAngles, amultchasers, zoffsets))
orbits = .05

filepath = time.strftime('gridsweep_%b%d_%H%M.pth')
with h5py.File(filepath, 'w') as h5file:
    for scenario_num, (initAngle, amultchaser, zoffset) in enumerate(initvars):
      print(scenario_num,"/",len(initvars))
      cx0 = np.array([amultchaser*a_target*np.cos(-initAngle),amultchaser*a_target*np.sin(-initAngle),zoffset])
      cv0mag = np.sqrt(mu/norm(cx0))
      cv0 = np.array([-cv0mag*np.sin(-initAngle),cv0mag*np.cos(-initAngle),0])
      unext = np.zeros((3,1)) #First Timestep, just use zero accel
    
      initdists = norm(t_hist[0:stepsPerOrbit,0,:]-cx0,axis=1)
      tback0 = stepsPerOrbit - np.argmin(initdists) + 1
    
      #Initialize states for this run
      tx=t_hist[stepsPerOrbit,0,:]
      tv=t_hist[stepsPerOrbit,1,:]
      cx=cx0.copy()
      cv=cv0.copy()
      tback=tback0
    
      steps = int(orbits*T_target)//step
      #At time 0, tx is at t_hist[stepsperorbit]
      if np.size(t_hist,axis=0) < (2*stepsPerOrbit)+steps:
          raise ValueError("Need longer precompute")
    
      #Initialize lists for plotting
      c_hist = np.zeros((steps,2,3)) # Shape (n, 2, 3)
      c_hist_ric = np.zeros((steps,2,3))
      tbackhist = np.zeros((steps,1)) # Shape (n,)
      #print("-"*(1+(steps//10)))
      for i in range(steps):
        ######### Logging ###########
          c_hist[i,0,:] = cx
          c_hist[i,1,:] = cv
          Tmat = ECI2RIC(tx, tv)
          c_hist_ric[i,0,:] = Tmat @ (cx-tx)
          c_hist_ric[i,1,:] = Tmat @ (cv-tv)
          coneconst = -1*(( -tv.T @ (cx-tx)/norm(cx-tx)) / (norm(tv))) + np.cos(conehalfangle) if norm(cx-tx)>1e-3 else 0
          speedconst = norm(cv-tv) - (g2*norm(cx-tx)) - g3 if norm(cx-tx) <= g1 and norm(cx-tx)>1e-3 else 0
          if coneconst > 0 or speedconst >0:
              raise ValueError("Scenario broke constraints. (initAngle, amultchaser, zoffset) = ("+str(initAngle) +" "+ str(amultchaser) +" "+ str(zoffset) +")")
          tbackhist[i] = tback
        ######### Control Calc ###########
          mint = 0.0001 #s
          maxt = tback #from last propagation
          if tback > 2:
              thresh = .5
          elif tback < 2:
              thresh = .01
          elif tback < .5:
              thresh = 0
              maxt = 0
          while maxt - mint > thresh:
              testTback = (maxt+mint)/2
              txsim = tx.copy()
              tvsim = tv.copy()
              success = OneOrbitNoLog(i, cx, cv, testTback)
              if success:
                  maxt = testTback #consts met
              else:
                  mint = testTback
          tback = maxt
          tsgIndex = stepsPerOrbit + i - tback
          Kt = indexInterp(K, tsgIndex, 0)
          tstate = indexInterp(t_hist, tsgIndex, 0);
          unext = -Kt@np.hstack([cx-tstate[0,:], cv-tstate[1,:]])
          if norm(unext)>.5:
              unext = unext * (.5/norm(unext))
    
    
          ######### Propagation ###########
          tx = t_hist[stepsPerOrbit+i+1,0,:]
          tv = t_hist[stepsPerOrbit+i+1,1,:]
          cx,cv = ECIprop(cx, cv, step, accel=unext)
      grp = h5file.create_group(f'scenario_{scenario_num:03d}')
      grp.create_dataset('chaser_pos', data=c_hist[:, 0, :])
      grp.create_dataset('chaser_vel', data=c_hist[:, 1, :])
      grp.create_dataset('target_pos', data=t_hist[stepsPerOrbit:stepsPerOrbit+steps, 0, :])
      grp.create_dataset('target_vel', data=t_hist[stepsPerOrbit:stepsPerOrbit+steps, 1, :])
      grp.create_dataset('tback', data=tbackhist)
      grp.create_dataset('chaser_pos_ric', data=c_hist_ric[:, 0, :])
      grp.create_dataset('chaser_vel_ric', data=c_hist_ric[:, 1, :])
      grp.attrs['initAngle'] = initAngle
      grp.attrs['amultchaser'] = amultchaser
      grp.attrs['zoffset'] = zoffset
      grp.attrs['tback0'] = float(tback0)
#%%
import matplotlib
matplotlib.use('tkAgg')
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import h5py
torch.manual_seed(1)

class NormDataset(Dataset):
    def __init__(self, hdf5_path):
        self.hdf5_path = hdf5_path
        with h5py.File(hdf5_path, 'r') as f:
            self.sequences = [k for k in sorted(f.keys()) if k.startswith('scenario_')]

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        with h5py.File(self.hdf5_path, 'r') as f:
            g = f[self.sequences[idx]]
            tback      = torch.FloatTensor(g['tback'][:])
            target_pos = torch.FloatTensor(g['target_pos'][:])
            chaser_pos = torch.FloatTensor(g['chaser_pos'][:])
            chaser_vel = torch.FloatTensor(g['chaser_vel'][:])
            target_vel = torch.FloatTensor(g['target_vel'][:])
            pos_ric    = torch.FloatTensor(g['chaser_pos_ric'][:])
            vel_ric    = torch.FloatTensor(g['chaser_vel_ric'][:])

        mag         = torch.norm(target_pos, dim=1, keepdim=True)
        state_local = torch.cat([pos_ric, vel_ric, mag], dim=1)
        state_abs   = torch.cat([chaser_pos, target_pos, chaser_vel, target_vel], dim=1)
        return state_local, state_abs, tback


dataset = NormDataset(filepath)
loader  = DataLoader(dataset, batch_size=1, shuffle=False)

tback_min, tback_max = float('inf'), float('-inf')
mins = {'local': torch.full((7,), float('inf')),  'abs': torch.full((12,), float('inf'))}
maxs = {'local': torch.full((7,), float('-inf')), 'abs': torch.full((12,), float('-inf'))}

for c, (s_loc, s_abs, tback) in enumerate(loader):
    s_loc, s_abs, tback = s_loc.squeeze(0), s_abs.squeeze(0), tback.squeeze(0)
    tback_min = min(tback_min, tback.min().item())
    tback_max = max(tback_max, tback.max().item())
    for key, s in [('local', s_loc), ('abs', s_abs)]:
        mins[key] = torch.minimum(mins[key], s.min(dim=0).values)
        maxs[key] = torch.maximum(maxs[key], s.max(dim=0).values)
    if (c + 1) % 5 == 0:
        print(f"Scenario {c+1}/{len(dataset)}")

torch.save({'tback_min': torch.tensor(tback_min), 'tback_max': torch.tensor(tback_max),
            'state_min_loc': mins['local'], 'state_max_loc': maxs['local'],
            'state_min_abs': mins['abs'],   'state_max_abs': maxs['abs']}, 'normsfor'+filepath[:filepath.find(".")]+'.pth')

